api_workers/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='accounts'
urlpatterns = [
    path('login/',views.login,name='login'),
    path("logout/", views.logout, name="logout"),
    path('register/', views.register, name='register'),
]

api_workers/api_workers/urls.py
from django.contrib import admin
from django.urls import path , include
from django.shortcuts import render
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workers.urls')),
    path('accounts/', include('accounts.urls')),
    path('HumanResource/',include('HumanResource.urls')),
    path('api-auth', include('rest_framework.urls')),
    path('.*', lambda request: render(request, '404.html'), name='404'),

]

api_workers/workers/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
# from . import models
from rest_framework import routers
router = routers.DefaultRouter()
router.register('jobs',views.JobView)
router.register('workers',views.WorkerView)
router.register('departments',views.DepartmentView)
urlpatterns = [
   path('',include(router.urls)),
]

api_workers/accounts/models.py
from django.db import models

# Create your models here.

api_workers/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import login,authenticate
# Create your views here.
"/"
@csrf_protect
def login(request):
    if request.method != 'GET':
        try:
            print('request - ',request)
            username = request.POST['username']
            password = request.POST['password']
            print(username,password)
            user = auth.authenticate(username=username, password=password)
            print(user)
            if user is not None:
                # print("User Login:  Username:" + username + '    Password:' + password)
                auth.login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                return redirect('/HumanResource/',{'showuserspictures':True})
            else:
                messages.info(request, 'Username or Password wrong!')
                return redirect('/HumanResource/', {'message': 'Username or Password wrong!'})
        except:
            return render(request, "/HumanResource/404.html")

        return render(request, 'accounts/login.html')
    else:
        if request.user.is_active:
            if request.user.is_authenticated:
                return redirect('/HumanResource/',{'showuserspictures':True})
    return render(request, 'accounts/login.html')

@csrf_protect
def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        if password1 == password2:
            print(password1)
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                print("Username Taken")
                return render(request, '/accounts/register.html')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email Taken')
                print("Email Taken")
                return render(request, '/accounts/register.html')
            else:
                user = User.objects.create_user(username=username, password=password1, email=email,first_name=first_name, last_name=last_name)
                user.save();
                users = [user]
                print(users)
                print('user created')
                auth.login(request, user)
                return redirect("/HumanResource/", {'users': users,'showuserspictures':True})
        else:
            messages.info(request, 'password not matching..')
            print('password not matching..')
            return render(request, 'accounts/register.html')
    else:
        print('request.method != POST')
        return render(request, 'accounts/register.html')

def logout(request):
    auth.logout(request)
    return redirect('/HumanResource/',{'showuserspictures':True})

api_workers/templates/accounts/login.html
<head>
    <title>Workers Login</title>
</head>
{% extends '../base.html' %}
{% load static %}
{% block content %}
 <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
		<div class="container login-container">
            <div class="row">
                <div class="col-md-6 login-form-1">
                    <div class="form-control-login">
                        <a class="form-control" style="text-align: center;"><h3>ACCOUNT LOGIN</h3></a>
                        <div class="form-group">
                            <input type="text" class="form-control"  name="username" placeholder="Your User Name *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password" placeholder="Your Password *" value="" />
                        </div>
                        {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{request.GET.next}}" />
                        {% endif %}
                        <div class="form-group">
                            <input type="submit" class="btnSubmit" value="Login" />
                        </div>

                    </div>
                </div>
			</div>
			<div id="dropDownSelect1"></div>
				{% for message in messages %}
				<h3 class="message"> {{message}}</h3>
				{% endfor %}
			</div>
		</div>
	</form>
{% endblock %}

api_workers/templates/accounts/register.html
<head>
    <title>Registration</title>
</head>
{% extends '../base.html' %}
{% load static %}
{% block content %}
    <form  action="{% url 'accounts:register' %}" method="post">
                {% csrf_token %}
		<div class="container login-container">
            <div class="row">
                <div class="col-md-6 login-form-1">
                    <div class="form-control-login">
                        <a class="form-control" style="text-align: center;"><h3>Account Register</h3></a>
                        <div class="form-group">
                            <input type="text" class="form-control"  name="first_name" placeholder="Your First Name *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control"  name="last_name" placeholder="Your Last Name *" value="" />
                        </div>
						<div class="form-group">
                            <input type="text" class="form-control"  name="username" placeholder="Your User Name *" value="" />
                        </div>
						<div class="form-group">
                            <input type="text" class="form-control"  name="email" placeholder="Your Email *" value="" />
                        </div>
                        <div class="form-group">
							<input type="password" class="form-control" name="password1" placeholder="Your Password *" value="" />
                        </div>
						<div class="form-group">
							<input type="password" class="form-control" name="password2" placeholder="Confirm Password *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btnSubmit" value="Sign Up" />
                        </div>

                    </div>
                </div>
			</div>
			<div id="dropDownSelect1"></div>
				{% for message in messages %}
				<h3 class="message"> {{message}}</h3>
				{% endfor %}
			</div>
		</div>
	</form>
{% endblock %}